---
title: 'Clines vs Clusters : Himalayan Birds abundance'
author: "Kushal K Dey"
date: "8/24/2018"
output: html_document
---

We try to interpret if we are seeing continuous clines or dicrete clusters in the
Himalayan birds abundance data.

```{r eval=TRUE, warning=FALSE, message=FALSE}
library(ecostructure)
library(Biobase)
```

## Load Data

```{r}
data("himalayan_birds")
species_abundance_counts <- t(exprs(himalayan_birds));
site_metadata <- pData(himalayan_birds)
elevation_metadata=site_metadata$Elevation;
east_west_dir = site_metadata$WorE;
```

## Ecos Fit

```{r echo=TRUE, eval=TRUE}
set.seed(1000)
fit <- ecos_fit(species_abundance_counts, K = 2, tol = 0.1, num_trials = 10)
```

```{r}
ecos_blocks(fit$omega,
            blocker_metadata = east_west_dir,
            order_metadata = elevation_metadata)
```

## Differences between clusters 

```{r}
tmp1 <- fit$theta[order(fit$theta[,2] - fit$theta[,1], decreasing = TRUE)[1:10],]
tmp2 <- fit$theta[order(fit$theta[,1] - fit$theta[,2], decreasing = TRUE)[1:10],]
```

## Low elevational cluster species 

```{r fig.height=13, fig.width=5}
par(mfrow=c(10, 2))

for(m in 1:10){
  tmp_dat <- species_abundance_counts[which(east_west_dir == "E"), rownames(tmp1)[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "E")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)

  tmp_dat <- species_abundance_counts[which(east_west_dir == "W"), rownames(tmp1)[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "W")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)
}

```

## High elevational cluster species 

```{r fig.height=13, fig.width=5}
par(mfrow=c(10, 2))

for(m in 1:10){
  tmp_dat <- species_abundance_counts[which(east_west_dir == "E"), rownames(tmp2)[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "E")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)

  tmp_dat <- species_abundance_counts[which(east_west_dir == "W"), rownames(tmp2)[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "W")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)
}

```

## Ecos Fit

```{r echo=TRUE, eval=TRUE}
set.seed(1000)
fit2 <- ecos_fit(species_abundance_counts, K = 3, tol = 0.1, num_trials = 10)
```

```{r}
ecos_blocks(fit$omega,
            blocker_metadata = east_west_dir,
            order_metadata = elevation_metadata)
```

## High elevational cluster species 

```{r fig.height=20, fig.width=5}
par(mfrow=c(10, 2))

for(m in 1:10){
  tmp_dat <- species_abundance_counts[which(east_west_dir == "E"), rownames(fit2$theta[order(fit2$theta[,1], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "E")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)

  tmp_dat <- species_abundance_counts[which(east_west_dir == "W"), rownames(fit2$theta[order(fit2$theta[,1], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "W")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)
}

```

## Low elevational cluster species 

```{r fig.height=20, fig.width=5}
par(mfrow=c(10, 2))

for(m in 1:10){
  tmp_dat <- species_abundance_counts[which(east_west_dir == "E"), rownames(fit2$theta[order(fit2$theta[,2], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "E")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)

  tmp_dat <- species_abundance_counts[which(east_west_dir == "W"), rownames(fit2$theta[order(fit2$theta[,2], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "W")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)
}

```


## Medium elevational cluster species 

```{r fig.height=20, fig.width=5}
par(mfrow=c(10, 2))

for(m in 1:10){
  tmp_dat <- species_abundance_counts[which(east_west_dir == "E"), rownames(fit2$theta[order(fit2$theta[,3], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "E")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)

  tmp_dat <- species_abundance_counts[which(east_west_dir == "W"), rownames(fit2$theta[order(fit2$theta[,3], decreasing = TRUE)[1:10],])[m]]
  ele_dat <- elevation_metadata[which(east_west_dir == "W")]
  plot(ele_dat, tmp_dat, pch= 20, xlab = "Elevation", ylab = "Abundance", cex = 1.5)
}

```
