---
title: "methclust global assemblages part 2"
author: "Kushal K Dey"
date: "1/24/2018"
output: html_document
---


We perform **methClust** on the global binary presence absence data of around 9500 bird species across approx 17,500 cells.

```{r setup, include=FALSE}
library(ecostructure)
library(Biobase)
library(rasterVis)
library(gtools)
library(bigalgebra)
library(sp)
library(rgdal)
library(ggplot2)
library(maps)
library(ggthemes)

```

## Plotting function of clusters

```{r}
latlong <- get(load("../data/LatLongCells_frame.rda"))
```

```{r}
world_map <- map_data("world")
world_map <- world_map[world_map$region != "Antarctica",] # intercourse antarctica

p <- ggplot() + coord_fixed() +
  xlab("") + ylab("")

#Add map to base plot
base_world_messy <- p + geom_map(data=world_map, map = world_map, aes(group=group, map_id=region), colour="white", fill="white", size=0.05, alpha=1/4) 

cleanup <- 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        axis.line = element_line(colour = "white"), legend.position="none",
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())

base_world <- base_world_messy + cleanup

```

```{r}
PlotAssemblageIdx <- function(dat){
  dat <- cbind.data.frame(latlong, dat)
colnames(dat) <- c("Latitude", "Longitude", "Value")
map_data_coloured <- 
  base_world +
  geom_point(data=dat, 
             aes(x=Latitude, y=Longitude, colour=Value), size=0.5) +
  scale_colour_gradient(low = "white", high = "black") 

map_data_coloured
}

```


## K = 26

```{r, echo=FALSE}

K26_global_topics <- get(load(file="../data/birds_meth_cluster_26.rda"))

topics_omega <- K26_global_topics$omega
PlotAssemblageIdx(topics_omega[,1])
PlotAssemblageIdx(topics_omega[,2])
PlotAssemblageIdx(topics_omega[,3])
PlotAssemblageIdx(topics_omega[,4])
PlotAssemblageIdx(topics_omega[,5])
PlotAssemblageIdx(topics_omega[,6])
PlotAssemblageIdx(topics_omega[,7])
PlotAssemblageIdx(topics_omega[,8])
PlotAssemblageIdx(topics_omega[,9])
PlotAssemblageIdx(topics_omega[,10])
PlotAssemblageIdx(topics_omega[,11])
PlotAssemblageIdx(topics_omega[,12])
PlotAssemblageIdx(topics_omega[,13])
PlotAssemblageIdx(topics_omega[,14])
PlotAssemblageIdx(topics_omega[,15])
PlotAssemblageIdx(topics_omega[,16])
PlotAssemblageIdx(topics_omega[,17])
PlotAssemblageIdx(topics_omega[,18])
PlotAssemblageIdx(topics_omega[,19])
PlotAssemblageIdx(topics_omega[,20])
PlotAssemblageIdx(topics_omega[,21])
PlotAssemblageIdx(topics_omega[,22])
PlotAssemblageIdx(topics_omega[,23])
PlotAssemblageIdx(topics_omega[,24])
PlotAssemblageIdx(topics_omega[,25])
PlotAssemblageIdx(topics_omega[,26])
```

## K = 29

```{r, echo=FALSE}

K29_global_topics <- get(load(file="../data/birds_meth_cluster_29.rda"))

topics_omega <- K29_global_topics$omega
PlotAssemblageIdx(topics_omega[,1])
PlotAssemblageIdx(topics_omega[,2])
PlotAssemblageIdx(topics_omega[,3])
PlotAssemblageIdx(topics_omega[,4])
PlotAssemblageIdx(topics_omega[,5])
PlotAssemblageIdx(topics_omega[,6])
PlotAssemblageIdx(topics_omega[,7])
PlotAssemblageIdx(topics_omega[,8])
PlotAssemblageIdx(topics_omega[,9])
PlotAssemblageIdx(topics_omega[,10])
PlotAssemblageIdx(topics_omega[,11])
PlotAssemblageIdx(topics_omega[,12])
PlotAssemblageIdx(topics_omega[,13])
PlotAssemblageIdx(topics_omega[,14])
PlotAssemblageIdx(topics_omega[,15])
PlotAssemblageIdx(topics_omega[,16])
PlotAssemblageIdx(topics_omega[,17])
PlotAssemblageIdx(topics_omega[,18])
PlotAssemblageIdx(topics_omega[,19])
PlotAssemblageIdx(topics_omega[,20])
PlotAssemblageIdx(topics_omega[,21])
PlotAssemblageIdx(topics_omega[,22])
PlotAssemblageIdx(topics_omega[,23])
PlotAssemblageIdx(topics_omega[,24])
PlotAssemblageIdx(topics_omega[,25])
PlotAssemblageIdx(topics_omega[,26])
PlotAssemblageIdx(topics_omega[,27])
PlotAssemblageIdx(topics_omega[,28])
PlotAssemblageIdx(topics_omega[,29])
```


## K = 31

```{r, echo=FALSE}

K31_global_topics <- get(load(file="../data/birds_meth_cluster_31.rda"))

topics_omega <- K31_global_topics$omega
PlotAssemblageIdx(topics_omega[,1])
PlotAssemblageIdx(topics_omega[,2])
PlotAssemblageIdx(topics_omega[,3])
PlotAssemblageIdx(topics_omega[,4])
PlotAssemblageIdx(topics_omega[,5])
PlotAssemblageIdx(topics_omega[,6])
PlotAssemblageIdx(topics_omega[,7])
PlotAssemblageIdx(topics_omega[,8])
PlotAssemblageIdx(topics_omega[,9])
PlotAssemblageIdx(topics_omega[,10])
PlotAssemblageIdx(topics_omega[,11])
PlotAssemblageIdx(topics_omega[,12])
PlotAssemblageIdx(topics_omega[,13])
PlotAssemblageIdx(topics_omega[,14])
PlotAssemblageIdx(topics_omega[,15])
PlotAssemblageIdx(topics_omega[,16])
PlotAssemblageIdx(topics_omega[,17])
PlotAssemblageIdx(topics_omega[,18])
PlotAssemblageIdx(topics_omega[,19])
PlotAssemblageIdx(topics_omega[,20])
PlotAssemblageIdx(topics_omega[,21])
PlotAssemblageIdx(topics_omega[,22])
PlotAssemblageIdx(topics_omega[,23])
PlotAssemblageIdx(topics_omega[,24])
PlotAssemblageIdx(topics_omega[,25])
PlotAssemblageIdx(topics_omega[,26])
PlotAssemblageIdx(topics_omega[,27])
PlotAssemblageIdx(topics_omega[,28])
PlotAssemblageIdx(topics_omega[,29])
PlotAssemblageIdx(topics_omega[,30])
PlotAssemblageIdx(topics_omega[,31])
```



## K = 33

```{r, echo=FALSE}

K33_global_topics <- get(load(file="../data/birds_meth_cluster_33.rda"))

topics_omega <- K33_global_topics$omega
PlotAssemblageIdx(topics_omega[,1])
PlotAssemblageIdx(topics_omega[,2])
PlotAssemblageIdx(topics_omega[,3])
PlotAssemblageIdx(topics_omega[,4])
PlotAssemblageIdx(topics_omega[,5])
PlotAssemblageIdx(topics_omega[,6])
PlotAssemblageIdx(topics_omega[,7])
PlotAssemblageIdx(topics_omega[,8])
PlotAssemblageIdx(topics_omega[,9])
PlotAssemblageIdx(topics_omega[,10])
PlotAssemblageIdx(topics_omega[,11])
PlotAssemblageIdx(topics_omega[,12])
PlotAssemblageIdx(topics_omega[,13])
PlotAssemblageIdx(topics_omega[,14])
PlotAssemblageIdx(topics_omega[,15])
PlotAssemblageIdx(topics_omega[,16])
PlotAssemblageIdx(topics_omega[,17])
PlotAssemblageIdx(topics_omega[,18])
PlotAssemblageIdx(topics_omega[,19])
PlotAssemblageIdx(topics_omega[,20])
PlotAssemblageIdx(topics_omega[,21])
PlotAssemblageIdx(topics_omega[,22])
PlotAssemblageIdx(topics_omega[,23])
PlotAssemblageIdx(topics_omega[,24])
PlotAssemblageIdx(topics_omega[,25])
PlotAssemblageIdx(topics_omega[,26])
PlotAssemblageIdx(topics_omega[,27])
PlotAssemblageIdx(topics_omega[,28])
PlotAssemblageIdx(topics_omega[,29])
PlotAssemblageIdx(topics_omega[,30])
PlotAssemblageIdx(topics_omega[,31])
PlotAssemblageIdx(topics_omega[,32])
PlotAssemblageIdx(topics_omega[,33])
```

